### ISSUE TITLE
Handle when working directory is not in a Git repo

### ISSUE THREAD

**Issue by Yoshanuikabundi** [Yoshanuikabundi/snakes_on_a_plane#2]
When running SOAP outside a Git repository, we get the following error:

```
Traceback (most recent call last):
  File "/home/joshmitchell/conda/bin/soap", line 33, in <module>
    sys.exit(load_entry_point('soap', 'console_scripts', 'soap')())
  File "/home/joshmitchell/Documents/snakes_on_a_plane/soap/_cli.py", line 45, in main
    cfg = soap.Config()
  File "/home/joshmitchell/Documents/snakes_on_a_plane/soap/config.py", line 189, in __init__
    git_root = get_git_root(".")
  File "/home/joshmitchell/Documents/snakes_on_a_plane/soap/utils.py", line 19, in get_git_root
    git_repo = Repo(path, search_parent_directories=True)
  File "/home/joshmitchell/conda/lib/python3.9/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/home/joshmitchell/conda/lib/python3.9/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

We should catch this error, possibly warn, and treat the working directory as the base of the git repo.

**Comment by Yoshanuikabundi** [comment]
Fixed in 07c4a3aaf174a605ffff08df201f23764b395b3d
